### PyMuPDF for Retrieval in RAG

* To convert PDF to text strings (Markdown)

In [16]:
import os
import sys
import pathlib
import gc

import pymupdf4llm
import pymupdf
import fitz

### Path

In [2]:
test_sample_1 = "/home/jerlshin/FieldOfInterest/My_Work/__PROJECTS__/TableExtraction/page_1.pdf"
test_sample_2 = "/home/jerlshin/FieldOfInterest/My_Work/__PROJECTS__/TableExtraction/page_2.pdf"

In [3]:
output = pathlib.Path("../output_images")

for item in output.iterdir():
    if(item.is_file()):
        print(item)

../output_images/page_2.png
../output_images/page_1.png

#### Multimodal LLM Application with PDF data

In [4]:
## To convert the pdf to markdwon

# with chunking
md_text = pymupdf4llm.to_markdown(doc=test_sample_1, page_chunks=True)

# with images
md_text_with_image_extract = pymupdf4llm.to_markdown(doc=test_sample_1, page_chunks=True, write_images=True, image_path="./images")

# embedding images ==> image data in base64 format
bed_images = pymupdf4llm.to_markdown(doc=test_sample_1, page_chunks=True, write_images=True, image_path="./images", embed_images=True)

# extracting words
chunks_words = pymupdf4llm.to_markdown(doc=test_sample_1, page_chunks=True, extract_words=True)

In [5]:
gc.collect()

100

#### Find and Extract Tables from PDFs

In [6]:
# it have list of all the pages
doc = pymupdf.open(test_sample_1)
print(doc.metadata)

# accessing pages
page = doc[0]
print(page)

{'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'creator': '', 'producer': 'pypdf', 'creationDate': '', 'modDate': '', 'trapped': '', 'encryption': None}
page 0 of /home/jerlshin/FieldOfInterest/My_Work/__PROJECTS__/TableExtraction/page_1.pdf

In [7]:

# find tables
find_table = page.find_tables(strategy="text")

# tables
table1 = find_table.tables[0]

table1.extract()

[['', '', '', '', 'Size', 'Recommended', 'Recommended', 'Special'],
 ['', 'IADC', '', 'r', 'ange,', 'WOB, lb/in.', 'rotary speed,', 'features/'],
 ['Bit Name', 'code', '', '', 'in.', 'diameter', 'rpm', 'usage*'],
 ['', '', '', '', '', '', '', ''],
 ['Surface set diamond', 'coring bits', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', ''],
 ['CB17', 'M613', '6-121/4', '', '', '250-3,500', '80-140', 'F'],
 ['', '', '', '', '', '', '', ''],
 ['Medium', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', ''],
 ['Insert roller cone bits', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', ''],
 ['M84', '615', '11 5/8, 17,', '171/2', '', '3,000-7,000', '300-80', 'X'],
 ['M84F',
  '617',
  '43/4, 51/2,',
  '61/4,',
  '61/2, 63/4, 77/8, 83/8,',
  '3,000-7,000',
  '80-40',
  'BX'],
 ['', '', '81/2, 83/4,', '91/2,', '97/8, 105/8, 12, 121/4', '', '', ''],
 ['M84FD',
  '617',
  '83/8, 81/2,',
  '8 3/4,',
  '121/4',
  '3,000-7,000',
  '80-40',
  'BXW'],
 ['MAF', '617', '77/8', '', '', '3,000-7,000', '80-40', 'AB'],
 ['MM88', '625', '121/4', '', '', '2,500-7,000', '150-80', 'MB'],
 ['M84CF', '627', '77/8, 83/4,', '11', '', '3,000-7,000', '80-40', 'BY'],
 ['M84CFD', '627', '81/2, 83/4', '', '', '3,000-7,000', '14824', 'BYW'],
 ['M85F', '627', '61/2, 63/4,', '77/8,', '83/4', '3,500-7,000', '80-40', 'BX'],
 ['M86CF', '627', '77/8', '', '', '3,000-7,000', '80-40', 'BY'],
 ['M89T', '627', '171/2', '', '', '2,500-7,000', '150-80', 'MB'],
 ['M89TF',
  '627',
  '57/8, 6, 61/',
  '8, 61/',
  '4, 61/2, 63/4, 77/8,',
  '3,500-7,000',
  '80-40',
  'BX'],
 ['M89TFD', '627', '81/2, 83/4,', '91/2', '', '3,500-7,000', '80-40', 'BXW'],
 ['M89F', '637', '77/8, 121/4', '', '', '4,000-7,000', '70-40', 'BY'],
 ['M89FD', '637', '97/8', '', '', '4,000-7,000', '70-40', 'BYW']]

We can use this to identify the rows of the table.

In [8]:
df = table1.to_pandas()

In [9]:
df

,Col0,Col1,Col2,Col3,4-Size,5-Recommended,6-Recommended,7-Special
0,,IADC,,r,"ange,","WOB, lb/in.","rotary speed,",features/
1,Bit Name,code,,,in.,diameter,rpm,usage*
2,,,,,,,,
3,Surface set diamond,coring bits,,,,,,
4,,,,,,,,
5,CB17,M613,6-121/4,,,"250-3,500",80-140,F
6,,,,,,,,
7,Medium,,,,,,,
8,,,,,,,,
9,Insert roller cone bits,,,,,,,
10,,,,,,,,
11,M84,615,"11 5/8, 17,",171/2,,"3,000-7,000",300-80,X
12,M84F,617,"43/4, 51/2,","61/4,","61/2, 63/4, 77/8, 83/8,","3,000-7,000",80-40,BX
13,,,"81/2, 83/4,","91/2,","97/8, 105/8, 12, 121/4",,,
14,M84FD,617,"83/8, 81/2,","8 3/4,",121/4,"3,000-7,000",80-40,BXW
15,MAF,617,77/8,,,"3,000-7,000",80-40,AB
16,MM88,625,121/4,,,"2,500-7,000",150-80,MB
17,M84CF,627,"77/8, 83/4,",11,,"3,000-7,000",80-40,BY
18,M84CFD,627,"81/2, 83/4",,,"3,000-7,000",14824,BYW
19,M85F,627,"61/2, 63/4,","77/8,",83/4,"3,500-7,000",80-40,BX
20,M86CF,627,77/8,,,"3,000-7,000",80-40,BY
21,M89T,627,171/2,,,"2,500-7,000",150-80,MB
22,M89TF,627,"57/8, 6, 61/","8, 61/","4, 61/2, 63/4, 77/8,","3,500-7,000",80-40,BX
23,M89TFD,627,"81/2, 83/4,",91/2,,"3,500-7,000",80-40,BXW
24,M89F,637,"77/8, 121/4",,,"4,000-7,000",70-40,BY
25,M89FD,637,97/8,,,"4,000-7,000",70-40,BYW

In [10]:
doc2 = pymupdf.open(test_sample_2)
page2 = doc2[0]

print(page2)

find_table2 = page2.find_tables(strategy="text")
table2 = find_table2.tables[0]
df2 = table2.to_pandas()

df2

page 0 of /home/jerlshin/FieldOfInterest/My_Work/__PROJECTS__/TableExtraction/page_2.pdf

,Col0,Col1,Re,comm,ended,for,these sy,stems,Col8,Col9,Col10,Col11,Pr,od
0,,,Wa,ter-ba,sed Fl,uids,,,,,,,Fu,nc
1,,,,,,,,,,,,,,
2,,,,,,,,,,,,gas,,
3,,,,rsed,,eated,,,Salt,,base,"oam,",,
4,,,,e,d,tr,,ds,d,,c-,", f",,ry
5,,,,-disp,perse,cium-,ymer,Soli,urate,base,theti,mist,mary,onda
6,radename,,Description,Non,Dis,Cal,Pol,Low,Sat,Oil-,Syn,"Air,",Pri,Sec
7,,,,,,,,,,,,,,
8,BARACARB 230,0,Sized calcium carbonate,X,X,X,X,X,X,X,X,,LO,W
9,BARACAT,,Cationic polymer solution,X,,X,X,X,X,,,,SH,FL
10,BARACHEK HV,,Cellulose derivative,X,,X,X,X,X,,,,V,FR
11,BARACHEK LV,,Cellulose derivative,X,,X,X,X,X,,,,FR,V
12,BARACOR 44,,Sulfide scavenger,X,X,X,X,X,X,X,X,,CO,
13,BARACOR 95,,Corrosion inhibitor,X,,,X,X,X,,,,CO,A
14,BARACOR 100,,Corrosion inhibitor,,,,,,,,,,CO,
15,BARACOR 129,,Powdered corrosion inihibitor,X,X,,X,X,X,,,,CO,
16,BARACOR 450,,High temp. corr. inh. for hi-density brines,,,,,,,,,,CO,TE
17,BARACOR 700,,Corrosion/scale inhibitor,X,,X,,,,,,X,CO,
18,BARACOR 1635,,Powdered oxygen corr. inhibitor,,,,,,,,,X,CO,
19,BARACTIVE,,Polar Activator,,,,,,,X,X,,V,FR
20,BARA-DEFOAM,1,Defoamer,X,X,X,X,X,,,,,D,SU
21,BARA-DEFOAM,HP,Defoamer,X,X,X,X,X,X,,,,D,
22,BARA-DEFOAM,W 300,Defoamer,X,X,X,X,X,X,,,,D,
23,BARAFILM,,Filming amine,X,X,X,X,X,X,,,X,CO,

#### Text Extraction Techniques

In [11]:
text = page.get_text()

print(text)

Page 10
Surface set diamond coring bits
CB17
M613
6-121/4
250-3,500
80-140
F
Medium
Insert roller cone bits
M84
615
11 5/8, 17, 171/2
3,000-7,000
300-80
X
M84F
617
43/4, 51/2, 61/4, 61/2, 63/4, 77/8, 83/8,
3,000-7,000
80-40
BX
81/2, 83/4, 91/2, 97/8, 105/8, 12, 121/4
M84FD
617
83/8, 81/2, 8 3/4, 121/4
3,000-7,000
80-40
BXW
MAF
617
77/8
3,000-7,000
80-40
AB
MM88
625
121/4
2,500-7,000
150-80
MB
M84CF
627
77/8, 83/4, 11
3,000-7,000
80-40
BY
M84CFD
627
81/2, 83/4
3,000-7,000
14824
BYW
M85F
627
61/2, 63/4, 77/8, 83/4
3,500-7,000
80-40
BX
M86CF
627
77/8
3,000-7,000
80-40
BY
M89T
627
171/2
2,500-7,000
150-80
MB
M89TF
627
57/8, 6, 61/8, 61/4, 61/2, 63/4, 77/8,
3,500-7,000
80-40
BX
M89TFD
627
81/2, 83/4, 91/2
3,500-7,000
80-40
BXW
M89F
637
77/8, 121/4
4,000-7,000
70-40
BY
M89FD
637
97/8
4,000-7,000
70-40
BYW
Size
Recommended
Recommended
Special
IADC
range,
WOB, lb/in.
rotary speed,
features/
Bit Name
code
in.
diameter
rpm
usage*
Security DBS

In [12]:
len(text)

947

Getting blocks

Previously, line breaks are inserted in the output, but no additional information is produced

In [13]:
blocks = page.get_text("blocks", sort=True)

In [14]:
blocks

[(211.19700622558594,
  14.255992889404297,
  274.77490234375,
  23.755992889404297,
  'Security DBS\n',
  7,
  0),
 (469.1999816894531,
  13.55999755859375,
  474.73199462890625,
  34.92084503173828,
  'Page 10\n',
  0,
  0),
 (18.00104522705078,
  33.464229583740234,
  454.5821228027344,
  55.1937370300293,
  'Size\nRecommended\nRecommended\nSpecial\nIADC\nrange,\nWOB, lb/in.\nrotary speed,\nfeatures/\nBit Name\ncode\nin.\ndiameter\nrpm\nusage*\n',
  6,
  0),
 (18.01020050048828,
  63.867000579833984,
  137.56129455566406,
  71.44300079345703,
  'Surface set diamond coring bits\n',
  1,
  0),
 (18.01020050048828,
  76.9530029296875,
  443.01336669921875,
  82.7249984741211,
  'CB17\nM613\n6-121/4\n250-3,500\n80-140\nF\n',
  2,
  0),
 (18.011199951171875,
  92.30191040039062,
  56.20109558105469,
  101.80191040039062,
  'Medium\n',
  3,
  0),
 (18.011199951171875,
  107.66621398925781,
  97.60493469238281,
  115.2422103881836,
  'Insert roller cone bits\n',
  4,
  0),
 (18.011199951171875,
  120.75221252441406,
  448.6162414550781,
  235.7242431640625,
  'M84\n615\n11 5/8, 17, 171/2\n3,000-7,000\n300-80\nX\nM84F\n617\n43/4, 51/2, 61/4, 61/2, 63/4, 77/8, 83/8,\n3,000-7,000\n80-40\nBX\n81/2, 83/4, 91/2, 97/8, 105/8, 12, 121/4\nM84FD\n617\n83/8, 81/2, 8 3/4, 121/4\n3,000-7,000\n80-40\nBXW\nMAF\n617\n77/8\n3,000-7,000\n80-40\nAB\nMM88\n625\n121/4\n2,500-7,000\n150-80\nMB\nM84CF\n627\n77/8, 83/4, 11\n3,000-7,000\n80-40\nBY\nM84CFD\n627\n81/2, 83/4\n3,000-7,000\n14824\nBYW\nM85F\n627\n61/2, 63/4, 77/8, 83/4\n3,500-7,000\n80-40\nBX\nM86CF\n627\n77/8\n3,000-7,000\n80-40\nBY\nM89T\n627\n171/2\n2,500-7,000\n150-80\nMB\nM89TF\n627\n57/8, 6, 61/8, 61/4, 61/2, 63/4, 77/8,\n3,500-7,000\n80-40\nBX\nM89TFD\n627\n81/2, 83/4, 91/2\n3,500-7,000\n80-40\nBXW\nM89F\n637\n77/8, 121/4\n4,000-7,000\n70-40\nBY\nM89FD\n637\n97/8\n4,000-7,000\n70-40\nBYW\n',
  5,
  0)]

**We can preprocess it and make a refined table. We can make a stringent pipeline for this.**

* It should recognize all the texts
* Make sure all the texts are recognized with bounding boxes accurately
* Continuous text should be joined with bounding boxes.
* Put that to Dataframe as you process
* Re-define the structure of the table

In [15]:
# Each list element is a block,
# It contains the position, text content, block number and block type

for block in blocks:
    print(block[4])
    print("="*50)

Security DBS

==================================================
Page 10

==================================================
Size
Recommended
Recommended
Special
IADC
range,
WOB, lb/in.
rotary speed,
features/
Bit Name
code
in.
diameter
rpm
usage*

==================================================
Surface set diamond coring bits

==================================================
CB17
M613
6-121/4
250-3,500
80-140
F

==================================================
Medium

==================================================
Insert roller cone bits

==================================================
M84
615
11 5/8, 17, 171/2
3,000-7,000
300-80
X
M84F
617
43/4, 51/2, 61/4, 61/2, 63/4, 77/8, 83/8,
3,000-7,000
80-40
BX
81/2, 83/4, 91/2, 97/8, 105/8, 12, 121/4
M84FD
617
83/8, 81/2, 8 3/4, 121/4
3,000-7,000
80-40
BXW
MAF
617
77/8
3,000-7,000
80-40
AB
MM88
625
121/4
2,500-7,000
150-80
MB
M84CF
627
77/8, 83/4, 11
3,000-7,000
80-40
BY
M84CFD
627
81/2, 83/4
3,000-7,000
14824
BYW
M85F
627
61/2, 63/4, 77/8, 83/4
3,500-7,000
80-40
BX
M86CF
627
77/8
3,000-7,000
80-40
BY
M89T
627
171/2
2,500-7,000
150-80
MB
M89TF
627
57/8, 6, 61/8, 61/4, 61/2, 63/4, 77/8,
3,500-7,000
80-40
BX
M89TFD
627
81/2, 83/4, 91/2
3,500-7,000
80-40
BXW
M89F
637
77/8, 121/4
4,000-7,000
70-40
BY
M89FD
637
97/8
4,000-7,000
70-40
BYW

==================================================

In [30]:
for block in blocks:
    print(block)
    print("="*50)

(211.19700622558594, 14.255992889404297, 274.77490234375, 23.755992889404297, 'Security DBS\n', 7, 0)
==================================================
(469.1999816894531, 13.55999755859375, 474.73199462890625, 34.92084503173828, 'Page 10\n', 0, 0)
==================================================
(18.00104522705078, 33.464229583740234, 454.5821228027344, 55.1937370300293, 'Size\nRecommended\nRecommended\nSpecial\nIADC\nrange,\nWOB, lb/in.\nrotary speed,\nfeatures/\nBit Name\ncode\nin.\ndiameter\nrpm\nusage*\n', 6, 0)
==================================================
(18.01020050048828, 63.867000579833984, 137.56129455566406, 71.44300079345703, 'Surface set diamond coring bits\n', 1, 0)
==================================================
(18.01020050048828, 76.9530029296875, 443.01336669921875, 82.7249984741211, 'CB17\nM613\n6-121/4\n250-3,500\n80-140\nF\n', 2, 0)
==================================================
(18.011199951171875, 92.30191040039062, 56.20109558105469, 101.80191040039062, 'Medium\n', 3, 0)
==================================================
(18.011199951171875, 107.66621398925781, 97.60493469238281, 115.2422103881836, 'Insert roller cone bits\n', 4, 0)
==================================================
(18.011199951171875, 120.75221252441406, 448.6162414550781, 235.7242431640625, 'M84\n615\n11 5/8, 17, 171/2\n3,000-7,000\n300-80\nX\nM84F\n617\n43/4, 51/2, 61/4, 61/2, 63/4, 77/8, 83/8,\n3,000-7,000\n80-40\nBX\n81/2, 83/4, 91/2, 97/8, 105/8, 12, 121/4\nM84FD\n617\n83/8, 81/2, 8 3/4, 121/4\n3,000-7,000\n80-40\nBXW\nMAF\n617\n77/8\n3,000-7,000\n80-40\nAB\nMM88\n625\n121/4\n2,500-7,000\n150-80\nMB\nM84CF\n627\n77/8, 83/4, 11\n3,000-7,000\n80-40\nBY\nM84CFD\n627\n81/2, 83/4\n3,000-7,000\n14824\nBYW\nM85F\n627\n61/2, 63/4, 77/8, 83/4\n3,500-7,000\n80-40\nBX\nM86CF\n627\n77/8\n3,000-7,000\n80-40\nBY\nM89T\n627\n171/2\n2,500-7,000\n150-80\nMB\nM89TF\n627\n57/8, 6, 61/8, 61/4, 61/2, 63/4, 77/8,\n3,500-7,000\n80-40\nBX\nM89TFD\n627\n81/2, 83/4, 91/2\n3,500-7,000\n80-40\nBXW\nM89F\n637\n77/8, 121/4\n4,000-7,000\n70-40\nBY\nM89FD\n637\n97/8\n4,000-7,000\n70-40\nBYW\n', 5, 0)
==================================================

In [31]:
block[:4]  # position of the text

(18.011199951171875, 120.75221252441406, 448.6162414550781, 235.7242431640625)

Getting as dictionary

In [33]:
pgdict = page.get_text("dict", sort=True)

print(pgdict.keys())

dict_keys(['width', 'height', 'blocks'])

In [50]:
for block in pgdict["blocks"]:
    print(block, "\n")
    print("="*50)

{'number': 7, 'type': 0, 'bbox': (211.19700622558594, 14.255992889404297, 274.77490234375, 23.755992889404297), 'lines': [{'spans': [{'size': 10.0, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold083.313', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Security DBS', 'origin': (211.19700622558594, 21.595993041992188), 'bbox': (211.19700622558594, 14.255992889404297, 274.77490234375, 23.755992889404297)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (211.19700622558594, 14.255992889404297, 274.77490234375, 23.755992889404297)}]}

==================================================
{'number': 0, 'type': 0, 'bbox': (469.1999816894531, 13.55999755859375, 474.73199462890625, 34.92084503173828), 'lines': [{'spans': [{'size': 6.0, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial050', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Page 10', 'origin': (470.3999938964844, 13.55999755859375), 'bbox': (469.1999816894531, 13.55999755859375, 474.73199462890625, 34.92084503173828)}], 'wmode': 0, 'dir': (0.0, 1.0), 'bbox': (469.1999816894531, 13.55999755859375, 474.73199462890625, 34.92084503173828)}]}

==================================================
{'number': 6, 'type': 0, 'bbox': (18.00104522705078, 33.464229583740234, 454.5821228027344, 55.1937370300293), 'lines': [{'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Size', 'origin': (200.64163208007812, 38.27423095703125), 'bbox': (200.64163208007812, 33.464229583740234, 213.3880615234375, 39.59373092651367)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (200.64163208007812, 33.464229583740234, 213.3880615234375, 39.59373092651367)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Recommended', 'origin': (282.6014404296875, 38.27423095703125), 'bbox': (282.6014404296875, 33.464229583740234, 329.30120849609375, 39.59373092651367)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (282.6014404296875, 33.464229583740234, 329.30120849609375, 39.59373092651367)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Recommended', 'origin': (354.6023864746094, 38.27423095703125), 'bbox': (354.6023864746094, 33.464229583740234, 401.3021545410156, 39.59373092651367)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (354.6023864746094, 33.464229583740234, 401.3021545410156, 39.59373092651367)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Special', 'origin': (429.721435546875, 38.27423095703125), 'bbox': (429.721435546875, 33.464229583740234, 452.1904296875, 39.59373092651367)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (429.721435546875, 33.464229583740234, 452.1904296875, 39.59373092651367)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'IADC', 'origin': (100.20144653320312, 46.07423400878906), 'bbox': (100.20144653320312, 41.26423263549805, 115.82685852050781, 47.393733978271484)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (100.20144653320312, 41.26423263549805, 115.82685852050781, 47.393733978271484)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'range,', 'origin': (197.41030883789062, 46.07423400878906), 'bbox': (197.41030883789062, 41.26423263549805, 216.86856079101562, 47.393733978271484)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (197.41030883789062, 41.26423263549805, 216.86856079101562, 47.393733978271484)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'WOB, lb/in.', 'origin': (288.9808654785156, 46.07423400878906), 'bbox': (288.9808654785156, 41.26423263549805, 323.16259765625, 47.393733978271484)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (288.9808654785156, 41.26423263549805, 323.16259765625, 47.393733978271484)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'rotary speed,', 'origin': (357.8346252441406, 46.07423400878906), 'bbox': (357.8346252441406, 41.26423263549805, 398.3922119140625, 47.393733978271484)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (357.8346252441406, 41.26423263549805, 398.3922119140625, 47.393733978271484)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'features/', 'origin': (427.5460205078125, 46.07423400878906), 'bbox': (427.5460205078125, 41.26423263549805, 454.5821228027344, 47.393733978271484)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (427.5460205078125, 41.26423263549805, 454.5821228027344, 47.393733978271484)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Bit Name', 'origin': (18.00104522705078, 53.874237060546875), 'bbox': (18.00104522705078, 49.06423568725586, 46.332984924316406, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (18.00104522705078, 49.06423568725586, 46.332984924316406, 55.1937370300293)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'code', 'origin': (100.4412612915039, 53.874237060546875), 'bbox': (100.4412612915039, 49.06423568725586, 115.65970611572266, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (100.4412612915039, 49.06423568725586, 115.65970611572266, 55.1937370300293)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'in.', 'origin': (203.48965454101562, 53.874237060546875), 'bbox': (203.48965454101562, 49.06423568725586, 210.69581604003906, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (203.48965454101562, 49.06423568725586, 210.69581604003906, 55.1937370300293)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'diameter', 'origin': (292.5321044921875, 53.874237060546875), 'bbox': (292.5321044921875, 49.06423568725586, 319.6257629394531, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (292.5321044921875, 49.06423568725586, 319.6257629394531, 55.1937370300293)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'rpm', 'origin': (371.82025146484375, 53.874237060546875), 'bbox': (371.82025146484375, 49.06423568725586, 384.1989440917969, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (371.82025146484375, 49.06423568725586, 384.1989440917969, 55.1937370300293)}, {'spans': [{'size': 6.5, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'usage*', 'origin': (430.4410400390625, 53.874237060546875), 'bbox': (430.4410400390625, 49.06423568725586, 451.47479248046875, 55.1937370300293)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (430.4410400390625, 49.06423568725586, 451.47479248046875, 55.1937370300293)}]}

==================================================
{'number': 1, 'type': 0, 'bbox': (18.01020050048828, 63.867000579833984, 137.56129455566406, 71.44300079345703), 'lines': [{'spans': [{'size': 8.0, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold066.688', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Surface set diamond coring bits', 'origin': (18.01020050048828, 69.76300048828125), 'bbox': (18.01020050048828, 63.867000579833984, 137.56129455566406, 71.44300079345703)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (18.01020050048828, 63.867000579833984, 137.56129455566406, 71.44300079345703)}]}

==================================================
{'number': 2, 'type': 0, 'bbox': (18.01020050048828, 76.9530029296875, 443.01336669921875, 82.7249984741211), 'lines': [{'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'CB17', 'origin': (18.01020050048828, 81.76300048828125), 'bbox': (18.01020050048828, 76.9530029296875, 34.23225402832031, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (18.01020050048828, 76.9530029296875, 34.23225402832031, 82.7249984741211)}, {'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'M613', 'origin': (99.01020050048828, 81.76300048828125), 'bbox': (99.01020050048828, 76.9530029296875, 114.99826049804688, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (99.01020050048828, 76.9530029296875, 114.99826049804688, 82.7249984741211)}, {'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': '6-121/4', 'origin': (153.01019287109375, 81.76300048828125), 'bbox': (153.01019287109375, 76.9530029296875, 175.00514221191406, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (153.01019287109375, 76.9530029296875, 175.00514221191406, 82.7249984741211)}, {'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': '250-3,500', 'origin': (291.3822021484375, 81.76300048828125), 'bbox': (291.3822021484375, 76.9530029296875, 320.5835876464844, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (291.3822021484375, 76.9530029296875, 320.5835876464844, 82.7249984741211)}, {'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': '80-140', 'origin': (367.9707336425781, 81.76300048828125), 'bbox': (367.9707336425781, 76.9530029296875, 388.1640930175781, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (367.9707336425781, 76.9530029296875, 388.1640930175781, 82.7249984741211)}, {'spans': [{'size': 6.5, 'flags': 4, 'bidi': 0, 'char_flags': 16, 'font': 'Arial054.188', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'F', 'origin': (439.0353698730469, 81.76300048828125), 'bbox': (439.0353698730469, 76.9530029296875, 443.01336669921875, 82.7249984741211)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (439.0353698730469, 76.9530029296875, 443.01336669921875, 82.7249984741211)}]}

==================================================
{'number': 3, 'type': 0, 'bbox': (18.011199951171875, 92.30191040039062, 56.20109558105469, 101.80191040039062), 'lines': [{'spans': [{'size': 10.0, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold083.313', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Medium', 'origin': (18.011199951171875, 99.64190673828125), 'bbox': (18.011199951171875, 92.30191040039062, 56.20109558105469, 101.80191040039062)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (18.011199951171875, 92.30191040039062, 56.20109558105469, 101.80191040039062)}]}

==================================================
{'number': 4, 'type': 0, 'bbox': (18.011199951171875, 107.66621398925781, 97.60493469238281, 115.2422103881836), 'lines': [{'spans': [{'size': 8.0, 'flags': 20, 'bidi': 0, 'char_flags': 16, 'font': 'Arial.Bold066.688', 'color': 0, 'alpha': 255, 'ascender': 0.800000011920929, 'descender': -0.20000000298023224, 'text': 'Insert roller cone bits', 'origin': (18.011199951171875, 113.56221008300781), 'bbox': (18.011199951171875, 107.66621398925781, 97.60493469238281, 115.2422103881836)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (18.011199951171875, 107.66621398925781, 97.60493469238281, 115.2422103881836)}]}

==================================================

Perform a text extraction on a limited area of the page

In [64]:
page

page 0 of /home/jerlshin/FieldOfInterest/My_Work/__PROJECTS__/TableExtraction/page_1.pdf

In [60]:
cropstart = page.search_for("Security DBS")

In [61]:
for rect in cropstart:
    print(rect)

In [62]:
sf = page.search_for("Security DBS", quads=True)

In [63]:
for rect in sf:
    print(rect)